import React from "react";
import {
  Atag,
  BackIcon,
  CardHeader,
  Cards,
  Content,
  Days,
  Heading,
  MainBackground,
  StyledTable,
  Subject,
  TableHeadear,
  Tdata,
  Thead,
  Trow,
} from "./ClassTimetableStyles";
import { Card } from "react-bootstrap";

function ClassTable() {
  return (
    <MainBackground>
      <Content>
        <Cards>
          <CardHeader>
            <Atag href="/dashboard">
              <BackIcon />
            </Atag>
            <Heading>Time Table</Heading>
          </CardHeader>
          <Card.Body>
            <StyledTable>
              <TableHeadear>
                <Trow>
                  <Thead>Timing</Thead>
                  <Thead>P1</Thead>
                  <Thead>P2</Thead>
                  <Thead>P3</Thead>
                  <Thead>P4</Thead>
                  <Thead>Lunch</Thead>
                  <Thead>P6</Thead>
                  <Thead>P7</Thead>
                  <Thead>P8</Thead>
                  <Thead>P9</Thead>
                </Trow>
              </TableHeadear>

              <tbody>
                <Trow>
                  <Days>Monday</Days>
                  <Tdata>
                    {" "}
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>

                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                </Trow>
                <Trow>
                  <Days>Tuesday</Days>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                </Trow>
                <Trow>
                  <Days>Wednesday</Days>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                </Trow>
                <Trow>
                  <Days>Theadursday</Days>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                </Trow>
                <Trow>
                  <Days>Friday</Days>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                </Trow>
                <Trow>
                  <Days>Saturday</Days>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Mathematics</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Social Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Lunch</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Sanskrit</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>English</Subject>
                  </Tdata>
                  <Tdata>
                    <Subject>Science</Subject>
                  </Tdata>
                </Trow>
              </tbody>
            </StyledTable>
          </Card.Body>
        </Cards>
      </Content>
    </MainBackground>
  );
}

export default ClassTable;
